### ISSUE TITLE
Not able to get octoscreen to the screen

### ISSUE THREAD

**Issue by daktylus** [Z-Bolt/OctoScreen#117]
Hi I have done a fresh install of octopi (Raspberry 3) and also my 3.5" GPIO LCD driver followed by Octoscreen installation. However after installing or rebooting the display showed me only the command line login even after octoscreen.service was active. After I used raspi-config to set the boot option to desktop autologin, the display shows some part of the boot log and when I login via putty i get this.

![image](https://user-images.githubusercontent.com/30987128/78594735-1cd6b400-7849-11ea-84ff-66232d5f65cd.png)

from here on nothing happens. Octoprint itself is usable via the browser.

What did I wrong and how can get octoscreen to work proberly?

**Comment by mdaneman** [comment]
Have you tried typing just "sudo systemctl start octoscreen.service"?  If this makes Octoscreen come up, then you just need to set it up as you window manager:
sudo dpkg-reconfigure octoscreen
and it should come up automatically when you boot to the desktop enviroment.
There's also a way to get it to come when you boot just to console, but try the above first.

**Comment by daktylus** [comment]
Yes I tried this several times without any success. :-(

**Comment by JeffB42** [comment]
@daktylus Could you follow the steps listed in the wiki (located at https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen) and then post a reply to this issue whether the steps listed work and the issue is resolved?  I'd like to start closing out all the display-related issues.

If it doesn't work,
1) make sure you use a Raspberry Pi 3B or Raspberry Pi 4
2) start with a fresh install of OctoPi
3) please take a picture of the screen

Thanks, 

Jeff

**Comment by daktylus** [comment]
After severals iterations, I got it to work. The Problem was the missing fbturbo during driver installation. The following worked for me (Raspberry Pi 3B + 3.5" RPi Display)

- Fresh Install Octopi (buster lite 0.17.0) 
- Install fbturbo. Needs to be installed before display driver!!
- Install display drivers
- Install Octodash 2.1.1

Tobias
