### ISSUE TITLE
Serve as a web app?

### ISSUE THREAD

**Issue by R0dri** [Z-Bolt/OctoScreen#135]
I have found that the TouchUI is to messy of an interface since it tries to take the page to the extreme of responsiveness which is powerful for plugins etc. But it is no so simple so I can use an old phone as an interface.

I find octoscreen much more minimalistic and adecuate for a touch UI. I tried to install and use it with VNC since I don’t have a TFT screen. But I failed and wondered, wouldn’t it easier to serve it as a web app?

I have no experience with go but I do with javascript/html5. How hard would it be serve octoscreen as a web app. Going further even deploying as a PWA could be amazing for push notifications. I am willing to develop a copy of this interface with html5/js implementing basic functions such as motion, play/pause, temp status and control and finally print files. I find it would be a better approach than modding TouchUI which is kinda heavy for old devices tbh.

Any insight, or advice moving forward? Sorry for the mini essay, I’m not so good expressing myself in a short manner.

Pd: although I have experience with octoprint api with postman as well as flask served pages. But I don’t know how to make an octoprint plugin.

**Comment by JeffB42** [comment]
> How hard would it be serve octoscreen as a web app

Incredibly hard.  It's a desktop app, built on X11.  Turning it into a web app means a complete rewrite, and even though I don't like GoLang (or GTK), I prefer to build on top of the existing codebase, rather than reinvent the wheel.

There's many ways to help out with the project...
* If you have a new feature request, document it and post (or even better, clone the repo, get up to building, and develop the feature)
* Monitor the issues here and help assist other users and help them troubleshoot issues.  Every hour I spend replying back and helping people out w/their config issues means one less hour I spend on coding new features or fixing bugs.
* Test out the app, in all areas, even the ones you don't use all the time.  If you find a bug, try to narrow it down and isolate it.  Even better, browse the code base and see if you can spot what the issue is.
