### ISSUE TITLE
Octoscreen service not starting on boot

### ISSUE THREAD

**Issue by drphil3d** [Z-Bolt/OctoScreen#30]
I'm not sure why it's not been registered as a service to start on boot. any ideas?

**Comment by shilbert01** [comment]
It is registered if you use `sudo systemctl enable octoscreen.service`

It will give you this output.
 
`Created symlink /etc/systemd/system/display-manager.service → /lib/systemd/system/octoscreen.service.
Created symlink /etc/systemd/system/graphical.target.wants/octoscreen.service → /lib/systemd/system/octoscreen.service.`

If it still does not come up check if it is running or not with

`sudo systemctl status octoscreen.service`

If it says active but "dead" this means it has been loaded but it not displayed. In my case I had to use raspi-config to boot into graphical environment.

You might want to have a look at issue #34 as well

**Comment by JeffB42** [comment]
@drphil3d is this still an issue?

**Comment by JeffB42** [comment]
Closed due to lack of response.

**Comment by ivizot** [comment]
Hey all,

I think the problem with "dead" service is related to the following line in  OctoScreen/debian/octoscreen.service:
`WantedBy=graphical.target`

In modern OctoPi images, there is no way (by default) to enable GUI autologin through `raspi-config` without installing of a display-manager.

Thus, the workaround might be to change target status required by OctoScreen?

**Comment by nathan-stewart** [comment]
Just wanted to underscore ivizot's comment as the key in 2023.

**Comment by FredFoo** [comment]
Ah, nice!

Had a look into the raspi-config script, interested in what it is doing.  So if you want to get this to work without installing another display manager, do this:

1. In raspi-config activate "Console Autologin" instead of desktop. This activates autologin
2. On the commandline, issue 'systemctl set-default graphical.target', to change the target manually

Thats it. 

BTW, you can manually activate autologin by creating the file `/etc/systemd/system/getty@tty1.service.d/autologin.conf` and add these lines:
`
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I $TERM
`
Is what the config script does.

**Comment by zapdogster** [comment]
Hey @FredFoo  - your solution worked perfectly for me. I tried all sorts of other "stuff" from other threads on here, and none of them worked. Yours did. THANKS!
