### ISSUE TITLE
No visual display extruder and bed after changing printer profile in octoprint

### ISSUE THREAD

**Issue by Mulle00** [Z-Bolt/OctoScreen#89]
No visual display extruder and bed after changing printer profile in octoprint (see photo).

I changed the profile in octoprint to work with my Prusa MK3s and MMU2s.
I choosed 5 extruders with shared nozzle.

![image](https://user-images.githubusercontent.com/25512372/74107648-98cabd80-4b72-11ea-9067-579dd7322cd5.png)

![IMG_20200209_172755](https://user-images.githubusercontent.com/25512372/74107594-0b876900-4b72-11ea-9375-9ce1f3eeea48.jpg)

**Comment by JeffB42** [comment]
@Mulle00  - a few things to mention:
1. after changing printer settings, OctoScreen needs to be restarted in order to pick up the changes.
2. OctoScreen only supports up to 4 extruders
3. Version 2.7.0 was just released, and it now supports printers with multiple extruders, but only a single hotend.
